project:
  type: website

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Generalized Linear Models"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - slides.qmd
      - labs.qmd
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



